# Generated by Django 4.2.7 on 2026-04-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('BSL', 'Basketbol Süper Ligi (Erkekler)'), ('KBSL', 'Kadınlar Basketbol Süper Ligi'), ('TBL', 'Türkiye Basketbol Ligi'), ('TKBL', 'Türkiye Kadınlar Basketbol Ligi')], max_length=10)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('week', models.CharField(blank=True, max_length=50)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('tbf_match_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('BSL', 'Basketbol Süper Ligi (Erkekler)'), ('KBSL', 'Kadınlar Basketbol Süper Ligi'), ('TBL', 'Türkiye Basketbol Ligi'), ('TKBL', 'Türkiye Kadınlar Basketbol Ligi')], max_length=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('matches_found', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', '1. Hakem'), ('2', '2. Hakem'), ('3', '3. Hakem'), ('commissioner', 'Komiser'), ('other', 'Diğer')], default='1', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.referee')),
            ],
            options={
                'unique_together': {('match', 'referee')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='referees',
            field=models.ManyToManyField(blank=True, through='tracker.MatchReferee', to='tracker.referee'),
        ),
    ]
