# Generated by Django 4.2.7 on 2026-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('BSL', 'Basketbol Süper Ligi (Erkekler)'), ('KBSL', 'Kadınlar Basketbol Süper Ligi'), ('TBL', 'Türkiye Basketbol Ligi'), ('TKBL', 'Türkiye Kadınlar Basketbol Ligi'), ('TB2L', 'Türkiye Basketbol 2. Ligi'), ('BGL', 'Basketbol Gençler Ligi Erkekler'), ('BGLK', 'Basketbol Gençler Ligi Kızlar'), ('EBBL', 'Erkekler Bölgesel Basketbol Ligi'), ('KBBL', 'Kadınlar Bölgesel Basketbol Ligi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='league',
            field=models.CharField(choices=[('BSL', 'Basketbol Süper Ligi (Erkekler)'), ('KBSL', 'Kadınlar Basketbol Süper Ligi'), ('TBL', 'Türkiye Basketbol Ligi'), ('TKBL', 'Türkiye Kadınlar Basketbol Ligi'), ('TB2L', 'Türkiye Basketbol 2. Ligi'), ('BGL', 'Basketbol Gençler Ligi Erkekler'), ('BGLK', 'Basketbol Gençler Ligi Kızlar'), ('EBBL', 'Erkekler Bölgesel Basketbol Ligi'), ('KBBL', 'Kadınlar Bölgesel Basketbol Ligi')], max_length=10),
        ),
    ]
